/* Original teaching positions. These are constrained exercises, not engine judgements. */
(function(root){
  'use strict';
  const topics = [
    ['reading','数气与计算','Liberties & reading','先数整块棋的气，再比较提子与逃跑；每一步都假设对方会应对。','Count the whole group’s liberties. Compare capturing and extending, assuming a reply.','只看自己想下的棋，会漏掉对方的打吃。','Reading only your own moves misses the opponent’s atari.'],
    ['shape','连接与棋形','Connection & shape','实接让棋子共用气。斜连和一间跳是否安全，要结合断点与周围的气判断。','Solid connections share liberties. Diagonals and jumps depend on cuts and nearby liberties.','靠得近不等于已经连在一起。','Nearby stones are not necessarily connected.'],
    ['attack','攻防与安定','Attack & safety','先检查自己的弱棋，再考虑攻击。被打吃时，除了延伸，也要寻找反提。','Check your weak groups before attacking. In atari, consider counter-capture as well as extension.','为了追吃一颗子，忽略自己的整块弱棋。','Chasing one stone while neglecting your own weak group.'],
    ['opening','布局与方向','Opening & direction','先观察角、边和棋子的配合。局部已经安定时，比较其他大场；仍有紧急问题时先应对。','Consider corners, sides and coordination. Look elsewhere after a local position settles; answer urgent threats first.','把“先角后边”当作不看局面的固定指令。','Treating “corners before sides” as a rule that ignores the position.'],
    ['endgame','死活与收官','Life & endgame','先确认死活和边界，再比较官子价值。比较时必须说明先后手条件和采用的计分规则。','Settle life and boundaries before comparing endgame values. Specify initiative and scoring assumptions.','把一个空洞当成活棋，或把未封闭的区域全部算成地。','Mistaking a hole for life, or counting an open area as secure territory.'],
    ['review','复盘与迁移','Review & transfer','先复述自己的判断，再找具体漏算。用不同方向的同类局面检验自己，避免只记答案坐标。','Explain your judgement before finding a missed reply. Test the idea in a transformed position rather than memorising coordinates.','只看胜率波动，没有找出下一盘可以执行的改进。','Watching win-rate changes without choosing an actionable improvement.']
  ].map(([id,title,titleEn,body,bodyEn,mistake,mistakeEn])=>({id,title,titleEn,body,bodyEn,mistake,mistakeEn}));
  const items=[];
  function board(id,topic,title,titleEn,sgf,answer,prompt,promptEn,explain,explainEn){items.push({id,topic,title,titleEn,sgf,answer,prompt,promptEn,explain,explainEn,kind:'board'});}
  function quiz(id,topic,title,titleEn,prompt,promptEn,options,optionsEn,answer,explain,explainEn){items.push({id,topic,title,titleEn,prompt,promptEn,options,optionsEn,answer,explain,explainEn,kind:'quiz'});}
  board('read-capture','reading','最后一口气','The last liberty','(;SZ[9]KM[0]PL[B]AW[dd]AB[cd][dc][de])',[4,3],'黑先，提掉白 D6。先数气，再落子。','Black: capture White D6. Count before playing.','E6 是白子的最后一口气。提子后，再检查黑棋自身的气。','E6 is White’s final liberty. After capturing, check Black’s liberties.');
  board('read-edge','reading','边角读棋','Reading the corner','(;SZ[9]KM[0]PL[B]AW[aa]AB[ba])',[0,1],'黑先，提掉角上的白子。','Black: capture the corner stone.','角上只有两个相邻点。B9 已被占据，最后一口气在 A8。','A corner has two neighbours. B9 is occupied; A8 is the final liberty.');
  quiz('read-check','reading','计算顺序','Reading order','读棋时，哪种顺序更可靠？','Which reading sequence is more reliable?',['我走、我再走','我走、对方最强应手、我再走','只看第一手能提几子'],['My move, then my next move','My move, their strongest reply, my response','Count captures on the first move only'],1,'每一层都要切换行棋方；对手没有义务配合你的计划。','Alternate the player at every step. Your opponent need not cooperate.');
  board('shape-connect','shape','保护断点','Protect the cut','(;SZ[9]KM[0]PL[B]AB[cd][ed]AW[dc])',[3,3],'黑先，用一手把 C6 与 E6 实接。','Black: connect C6 and E6 directly in one move.','D6 同时邻接两颗黑子，成为同一块。','D6 touches both stones and joins them into one group.');
  board('shape-cut','shape','切断斜连','Cut a diagonal','(;SZ[9]KM[0]PL[B]AW[dd][ee]AB[de])',[4,3],'黑先，占据另一个直接连接点。','Black: occupy the remaining direct connection point.','E6 与 D5 配合，阻止白棋在这两个点直接连接；不代表已经吃住白棋。','E6 and D5 block both direct connection points. This does not prove White is captured.');
  quiz('shape-check','shape','形状不等于连接','Shape versus connection','两颗同色棋子仅斜着相邻，它们是否共用气？','Do two same-colour stones touching only diagonally share liberties?',['一定共用','不会因此成为同一块','只在角上共用'],['Always','They are not one connected group','Only in a corner'],1,'规则只把上下左右的同色相邻棋子算作相连。','Only orthogonally adjacent stones are connected under the rules.');
  board('attack-save','attack','先救弱棋','Save the weak stone','(;SZ[9]KM[0]PL[B]AB[dd]AW[cd][dc][de])',[4,3],'黑先，延伸 D6，增加这块棋的气。','Black: extend D6 to gain liberties.','E6 让黑棋从一口气增加到三口气；这只是局部解围。','E6 increases Black’s liberties from one to three; it is a local escape.');
  board('attack-capture','attack','反提解围','Counter-capture','(;SZ[9]KM[0]PL[B]AB[dd][ec][fd]AW[cd][dc][ed])',[4,4],'黑先，提掉相邻的白 E6。','Black: capture the adjacent White E6.','E5 提掉白子，腾出的 E6 也成为黑棋的气。','E5 captures White and frees E6 as a liberty for Black.');
  quiz('attack-check','attack','攻击前检查什么','Before attacking','准备攻击时，先检查什么？','What should you check before attacking?',['自己的弱棋、断点与气','对方棋子的数量就够了','攻击一定比防守好'],['Your weak groups, cuts and liberties','Only the number of enemy stones','Attacking is always better'],0,'先保证攻击的棋子有支援和出路，避免攻着攻着自己被切断。','Check support and escape routes so the attacking stones do not become isolated.');
  quiz('opening-direction','opening','局部结束以后','After a local sequence','假设局部双方均已安定、没有紧急断点，下一步应怎样选择？','Assume both local groups are settled with no urgent cuts. What next?',['继续在原地补每一个空点','比较全盘尚未占据的大场','立即停着'],['Fill every local empty point','Compare large points across the board','Pass immediately'],1,'局部安定后，把视线移回全盘；具体落点仍需结合棋子配合。','After settling locally, compare the whole board and stone coordination.');
  board('opening-urgent','opening','大场之前的急所','Urgency before expansion','(;SZ[9]KM[0]PL[B]AB[dd]AW[cd][dc][de])',[4,3],'本题要求先救被打吃的 D6，用延伸增加气。','For this exercise, save D6 by extending its liberties first.','先识别局部急迫性，再谈全盘大场。实战是否弃子，还需比较全局价值。','Identify urgency before expansion. Whether to sacrifice in a real game requires whole-board comparison.');
  quiz('opening-check','opening','理解布局原则','Opening principles','“先角后边”应如何使用？','How should “corners before sides” be used?',['作为观察方向，同时检查紧急局面','无论发生什么都先占角','每盘必须下同一套顺序'],['As a guide while checking urgent positions','Take a corner regardless of threats','Repeat an identical sequence every game'],0,'原则帮助比较，不能代替读棋。','Principles guide comparison; they do not replace reading.');
  board('endgame-eyes','endgame','先确认活棋','Establish life first','(;SZ[9]KM[0]PL[B]AB[cc][dc][ec][fc][gc][cd][gd][ce][de][ee][fe][ge])',[4,3],'黑先，将内部三点空间分成两个独立眼。','Black: split the internal three-point space into two eyes.','E6 把 D6 和 F6 分开，形成两个真眼。','E6 separates D6 and F6 into two true eyes.');
  quiz('endgame-value','endgame','比较同条件官子','Compare like-for-like','假设两处都是后手官子，已用相同方法算出净价值 4 目与 2 目，且没有其他急所。先选哪处？','Assume two gote endgames have net values of 4 and 2 points under the same method, with no urgent moves. Which first?',['2 目','4 目','无法比较任何官子'],['2 points','4 points','Endgames can never be compared'],1,'在本题的相同先后手条件下，先收价值较大的官子；条件变化就要重算。','Under these equal initiative assumptions, take the larger value. Recalculate if conditions change.');
  quiz('endgame-check','endgame','何时可以数地','Before counting territory','一块区域还有缺口、棋块死活也未明确，应该怎样处理？','An area is open and its group’s life is unsettled. What should you do?',['全部算成自己的地','先判断死活与边界，再点目','忽略双方规则差异'],['Count all of it as yours','Resolve life and boundaries before counting','Ignore rule differences'],1,'尚有争议的区域不能当成已经确定的地。','Contested space is not settled territory.');
  board('review-transfer','review','换个方向再读','Transfer the idea','(;SZ[9]KM[0]PL[B]AW[ff]AB[ef][fe][gf])',[5,6],'黑先，提掉 F4。不要沿用上一题的坐标。','Black: capture F4. Read anew rather than repeating a coordinate.','F3 是最后一口气。掌握的是数气方法，而不是 E6 这个答案。','F3 is the final liberty. The skill is counting liberties, not memorising E6.');
  quiz('review-method','review','从结果到原因','From result to cause','复盘发现一手损目很大，下一步最有用的是？','A move loses many points in review. What is the useful next step?',['只记住损目数字','找出漏看的应手，试一个替代变化','立即认定自己退步'],['Memorise the loss number','Identify the missed reply and test an alternative','Conclude you have become weaker'],1,'把评价转成能复现的具体问题，必要时加深分析复核。','Turn the evaluation into a reproducible question; deepen analysis when needed.');
  quiz('review-check','review','给下一盘一个目标','A goal for the next game','哪条复盘笔记最容易落实？','Which review note is most actionable?',['以后下好一点','每次接触战前，检查自己的断点和气','以后绝不犯错'],['Play better','Before contact fighting, check my cuts and liberties','Never make a mistake again'],1,'选择可以在落子前执行的小检查，比笼统评价更有帮助。','Choose a small check you can perform before a move.');
  const guides=[
    {id:'leesedol-1',title:'李世石第 1 局：从开局看配合',titleEn:'Lee Sedol 1: opening coordination',stops:[4,20,40],question:'先观察四个角，再看最近一手与己方棋子的距离。它是在扩张、接近对手，还是补强？',questionEn:'Compare the four corners and the last move’s distance from friendly stones. Is it expanding, approaching or reinforcing?',note:'前四手便于辨认开局的角部配置；随后对照第 20、40 手，观察棋子如何从角向边延伸。先描述位置关系，再用复盘分析比较具体选择。',noteEn:'Use move 4 to identify the initial corner arrangement, then compare moves 20 and 40 as stones extend toward the sides. Describe relationships before comparing choices in Review.'},
    {id:'leesedol-2',title:'李世石第 2 局：观察与猜着',titleEn:'Lee Sedol 2: observe before guessing',stops:[20,36,60],question:'揭晓下一手前，先说出你想解决的问题。实战选择与自己的目标是否相同？',questionEn:'Before revealing the next move, name the problem you want to solve. Does the played move serve the same goal?',note:'猜着比较的是实战落点，不是唯一正确答案。按第 20、36、60 手分段观察；猜错时先比较目的，不直接认定自己的着法是坏棋。',noteEn:'Guess mode compares with the played move, not a unique correct answer. Pause at 20, 36 and 60. Compare intentions before judging your alternative.'},
    {id:'may2017-1',title:'柯洁第 1 局：找到复盘问题',titleEn:'Ke Jie 1: frame a review question',stops:[30,80,140],question:'找一块你不确定是否安定的棋。先检查气、连接和出路，再提出一个具体复盘问题。',questionEn:'Find a group whose safety you are unsure of. Check liberties, connections and escape routes, then ask a specific review question.',note:'这三个停靠点用于练习观察开局、中盘与后续局面的变化，不代表 AI 判定的失误点。需要评价优劣时，把棋谱送到复盘，核对规则与搜索预算。',noteEn:'These checkpoints support observation across phases; they are not AI-labelled mistakes. To evaluate moves, open Review and check rules and search budget.'}
  ];
  root.GoTCurriculum={topics,items,guides};
})(window);
