/* Learning habits and match calibration. Stores summaries only, never boards. */
(function(root){
  'use strict';
  const KEY='got.growth';
  const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  function read(){try{const x=JSON.parse(root.localStorage.getItem(KEY));return x&&x.days&&typeof x.days==='object'&&!Array.isArray(x.days)&&Object.values(x.days).every(Array.isArray)&&Array.isArray(x.matches)&&x.matches.every(r=>r&&['builtin','gtp'].includes(r.engine)&&Number.isInteger(r.level)&&r.level>=1&&r.level<=9&&[0,.5,1].includes(r.outcome))&&Array.isArray(x.done)?x:{days:{},matches:[],done:[]};}catch(e){return {days:{},matches:[],done:[]};}}
  function save(x){try{root.localStorage.setItem(KEY,JSON.stringify(x));}catch(e){/* private mode */}}
  function activity(kind,id){const x=read(),k=day();const items=x.days[k]||[];const token=kind+':'+id;if(!items.includes(token)){items.push(token);x.days[k]=items.slice(-100);save(x);}return items.length;}
  function nextLevel(engine){const rows=read().matches.filter(x=>x.engine===engine);if(!rows.length)return 4;const last=rows.at(-1);return Math.max(1,Math.min(9,last.level+(last.outcome>0.5?1:last.outcome<0.5?-1:0)));}
  function result(engine,level,outcome){if(!['builtin','gtp'].includes(engine)||(!Number.isInteger(level)||level<1||level>9)||![0,0.5,1].includes(outcome))return;const x=read();x.matches.push({engine,level,outcome,date:day()});x.matches=x.matches.slice(-60);save(x);activity('assessment',x.matches.length+':'+Date.now());}
  function estimate(engine){const rows=read().matches.filter(x=>x.engine===engine).slice(-8);if(rows.length<3)return null;const value=rows.reduce((s,r)=>s+r.level+(r.outcome-.5),0)/rows.length;return {level:Math.max(1,Math.min(9,Math.round(value))),count:rows.length};}
  const lessons=[
    ['read','先读清，再落子','Read before playing','每次先数双方的气，再找打吃、连接和断点。按“我走—对方最强应手—我再走”读三手；看不清时先保护弱棋。','Count liberties, then look for atari, connections and cuts. Read your move, the strongest reply, and your response. Protect weak groups when unsure.','每天选 3 道能认真读完的题；先不点提示，答错后说明漏算了哪一手。','Read three manageable problems daily without hints. After a miss, identify the reply you overlooked.','practice'],
    ['shape','让棋子一起工作','Make stones work together','连接能减少被切断后的负担；不要只追着对方跑。每次接触战前，检查自己的断点和出路，再考虑攻击。','Connections reduce the burden of separated groups. Before contact fighting, check your own cuts and escape routes.','下一盘只观察一个问题：我是不是留下了两块需要同时逃跑的弱棋？','In your next game, watch for two weak groups that need to run at once.','play'],
    ['opening','从局部走向全盘','See the whole board','开局先考虑角、边与棋子配合。局部暂时安定后，停下来找全盘最大的方向；不要为了几颗子让整块棋受攻。','In the opening consider corners, sides and coordination. When a local position settles, look for the largest whole-board direction.','读一局名局的前 30 手，每次停下写出下一手想解决的问题，再揭晓实战。','Study the first 30 moves of a record. Before revealing each move, name the problem it should solve.','library'],
    ['review','复盘只抓三个转折','Find three turning points','先自己回想哪里开始难下，再用 AI 检查。每局最多选三个转折，解释实战的问题，试下一个更稳妥的方案。低搜索量结论先复核。','Recall where the game became difficult before consulting AI. Pick up to three turning points and try a safer alternative. Recheck low-search conclusions.','复盘一盘自己的棋，留下“我漏看了什么”和“下次先检查什么”两句笔记。','Review one of your games. Note what you missed and what you will check next time.','review'],
    ['endgame','收官时比较先后手','Compare endgame choices','先确认双方死活，再比较边界。能迫使对方应手的收官与走完轮到对方的大场不同；不要把还有争议的棋直接当成死棋。','Settle life and death before comparing boundaries. Distinguish forcing endgame moves from moves that give away the initiative.','终局先自己点目，再看 AI 参考；找出一处归属判断不同的区域。','Count a finished position yourself, then compare with AI and examine one disagreement.','play'],
    ['routine','建立可持续的训练循环','Build a repeatable routine','每周安排两盘认真对局、两次短复盘和少量每日读题。难题卡住就降一级；同类错误反复出现时，再集中练习。用几周的变化判断进步。','Plan two thoughtful games, two short reviews and a little daily reading each week. Reduce difficulty when stuck and focus on recurring mistakes. Evaluate progress over weeks.','本周选择一个主题：气、连接、弱棋或收官。周末回顾是否比上周少犯一次同类错误。','Choose one theme this week: liberties, connections, weak groups or endgame. At week end, check whether that mistake happened less often.','practice']
  ];
  function render(en){const t=(z,e)=>en?e:z,x=read();return `<section class="growth-path"><h2>${t('入门之后，怎样继续进步','Your path beyond the basics')}</h2><p>${t('先学一个方法，再去棋盘上实践。完成练习后记录一次，逐周回看自己的变化。','Learn one method, apply it on the board, then record your practice and reflect each week.')}</p>${lessons.map(([id,z,e,body,bodyEn,task,taskEn,target],i)=>`<details class="growth-lesson" ${i===0?'open':''}><summary>${i+1}. ${t(z,e)}${(x.done||[]).includes(id)?t(' · 已实践',' · Practised'):''}</summary><p>${t(body,bodyEn)}</p><p><strong>${t('这次练什么：','Your practice: ')}</strong>${t(task,taskEn)}</p><div class="growth-actions"><button type="button" class="btn primary" data-growth-go="${target}">${t('去实践','Practise')}</button><button type="button" class="btn ghost" data-growth-done="${id}" aria-pressed="${(x.done||[]).includes(id)}">${t('记录已实践','Mark practised')}</button></div></details>`).join('')}<section class="growth-assessment"><h2>${t('找到势均力敌的对手','Find a well-matched opponent')}</h2><p>${t('19 路连续测评，每盘结束后根据胜负自动调档。至少完成 3 盘再显示参考；建议 5–8 盘。引擎档位未经人类段位校准，结果不是正式评级。','Play consecutive 19×19 games. Difficulty adjusts after each result; a reference appears after three games (five to eight recommended). Engine levels are not calibrated human ranks.')}</p>${['builtin','gtp'].map(engine=>{const a=estimate(engine);return `<p>${engine==='gtp'?'KataGo':t('内置 AI','Built-in AI')} · ${a?t('参考 ','Reference ')+root.Strength.rankText(root.Strength.rankNum(a.level,engine==='gtp'),en?'en':'zh')+' · '+a.count+t(' 盘',' games'):t('样本不足','Not enough games')}</p>`;}).join('')}<button type="button" class="btn primary" data-growth-assess>${t('开始下一盘测评','Start next assessment game')}</button><p class="dialog-hint">${t('将开始新棋局。需要保留当前对局时，请先导出棋谱。中途离开可返回继续；进入复盘、使用分析或悔棋、新建或导入其他棋局会取消本盘测评。','Starts a fresh game. Export your current record first if needed. You can return after navigating away; review, analysis, undo, or starting/importing another game cancels this assessment.')}</p></section></section>`;}
  function heatmap(host,en){if(!host)return;host.replaceChildren();const x=read(),end=new Date(),start=new Date(end);start.setDate(end.getDate()-90);start.setDate(start.getDate()-((start.getDay()+6)%7));let active=0;const grid=document.createElement('div');grid.className='activity-grid';grid.setAttribute('role','list');for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const key=day(d),count=(x.days[key]||[]).length;if(count)active++;const cell=document.createElement('span');cell.className='activity-day';cell.dataset.level=String(Math.min(4,count));cell.title=key+' · '+count+(en?' activities':' 次活动');cell.setAttribute('role','listitem');cell.setAttribute('aria-label',cell.title);grid.append(cell);}const note=document.createElement('p');note.textContent=en?`${active} active days · last 13 weeks · darker means more activity`:`近 13 周活跃 ${active} 天 · 颜色越深，练习越多`;host.append(grid,note);}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-growth-go],[data-growth-done],[data-growth-assess]');if(!b)return;if(b.hasAttribute('data-growth-assess'))document.dispatchEvent(new CustomEvent('got:assessment-start'));else if(b.dataset.growthGo)document.dispatchEvent(new CustomEvent('got:home-action',{detail:b.dataset.growthGo}));else{const x=read(),id=b.dataset.growthDone;x.done=x.done||[];if(!x.done.includes(id))x.done.push(id);save(x);activity('method',id);root.GoTLearning?.render();}});
  document.addEventListener('got:learning-lesson-event',e=>{if(e.detail?.type==='solve')activity('lesson',e.detail.lessonId);});
  document.addEventListener('got:learning-library-event',e=>{if(Number(e.detail?.index)>0)activity('record',e.detail.libraryId);});
  document.addEventListener('got:problem-progress',()=>activity('problems','practice'));
  function merge(raw){if(!raw||typeof raw!=='object')return;const x=read();for(const [key,items] of Object.entries(raw.days||{}).slice(-730)){if(/^\d{4}-\d{2}-\d{2}$/.test(key)&&Array.isArray(items))x.days[key]=[...new Set([...(x.days[key]||[]),...items.filter(i=>typeof i==='string'&&i.length<160)])].slice(-100);}x.done=[...new Set([...(x.done||[]),...(Array.isArray(raw.done)?raw.done:[])])].filter(id=>lessons.some(l=>l[0]===id));const valid=(Array.isArray(raw.matches)?raw.matches:[]).filter(r=>r&&['builtin','gtp'].includes(r.engine)&&Number.isInteger(r.level)&&r.level>=1&&r.level<=9&&[0,.5,1].includes(r.outcome)&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)).map(({engine,level,outcome,date})=>({engine,level,outcome,date}));const known=new Set(x.matches.map(r=>JSON.stringify(r)));for(const r of valid)if(!known.has(JSON.stringify(r))){x.matches.push(r);known.add(JSON.stringify(r));}x.matches=x.matches.slice(-60);save(x);}
  root.GoTGrowth={day,read,activity,nextLevel,result,estimate,render,heatmap,merge};
})(window);
