/* Learning habits and match calibration. Stores summaries only, never boards. */
(function(root){
  'use strict';
  const KEY='got.growth';
  const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  function read(){try{const x=JSON.parse(root.localStorage.getItem(KEY));return x&&x.days&&typeof x.days==='object'&&!Array.isArray(x.days)&&Object.values(x.days).every(Array.isArray)&&Array.isArray(x.matches)&&x.matches.every(r=>r&&['builtin','gtp','b6','b18'].includes(r.engine)&&Number.isInteger(r.level)&&r.level>=1&&r.level<=9&&[0,.5,1].includes(r.outcome))&&Array.isArray(x.done)?x:{days:{},matches:[],done:[]};}catch(e){return {days:{},matches:[],done:[]};}}
  function save(x){try{root.localStorage.setItem(KEY,JSON.stringify(x));}catch(e){/* private mode */}}
  function activity(kind,id){const x=read(),k=day();const items=x.days[k]||[];const token=kind+':'+id;if(!items.includes(token)){items.push(token);x.days[k]=items.slice(-100);save(x);}return items.length;}
  function nextLevel(engine){
    const rows=read().matches.filter(x=>x.engine===engine);if(!rows.length)return 4;
    const last=rows.at(-1),recent=rows.slice(-2);
    const confirmed=recent.length===2&&recent.every(r=>r.level===last.level&&r.outcome===last.outcome);
    return Math.max(1,Math.min(9,last.level+(confirmed?(last.outcome>.5?1:last.outcome<.5?-1:0):0)));
  }
  function result(engine,level,outcome){if(!['builtin','gtp','b6','b18'].includes(engine)||(!Number.isInteger(level)||level<1||level>9)||![0,0.5,1].includes(outcome))return;const x=read();x.matches.push({engine,level,outcome,date:day()});x.matches=x.matches.slice(-60);save(x);activity('assessment',x.matches.length+':'+Date.now());}
  function estimate(engine){
    const rows=read().matches.filter(x=>x.engine===engine).slice(-8);if(rows.length<3)return null;
    const levels=rows.map(r=>r.level+r.outcome-.5).sort((a,b)=>a-b);
    const clamp=n=>Math.max(1,Math.min(9,n)),level=clamp(Math.round(levels[Math.floor(levels.length/2)]));
    const low=clamp(Math.floor(levels[0])),high=clamp(Math.ceil(levels.at(-1)));
    return {level,count:rows.length,low,high,stable:rows.length>=5&&high-low<=2};
  }
  function rankLabel(engine, level, en) {
    const kind = engine === 'builtin' ? 'mcts' : engine === 'gtp' ? 'b18' : engine;
    return root.Strength?.rankTextFor ? root.Strength.rankTextFor(kind, level, en ? 'en' : 'zh') : (en ? 'Level ' : '档位 ') + level;
  }
  const lessons=[
    ['read','先读清，再落子','Read before playing','每次先数双方的气，再找打吃、连接和断点。按“我走—对方最强应手—我再走”读三手；看不清时先保护弱棋。','Count liberties, then look for atari, connections and cuts. Read your move, the strongest reply, and your response. Protect weak groups when unsure.','每天选 3 道能认真读完的题；先不点提示，答错后说明漏算了哪一手。','Read three manageable problems daily without hints. After a miss, identify the reply you overlooked.','practice'],
    ['shape','让棋子一起工作','Make stones work together','连接能减少被切断后的负担；不要只追着对方跑。每次接触战前，检查自己的断点和出路，再考虑攻击。','Connections reduce the burden of separated groups. Before contact fighting, check your own cuts and escape routes.','下一盘只观察一个问题：我是不是留下了两块需要同时逃跑的弱棋？','In your next game, watch for two weak groups that need to run at once.','play'],
    ['opening','从局部走向全盘','See the whole board','开局先考虑角、边与棋子配合。局部暂时安定后，停下来找全盘最大的方向；不要为了几颗子让整块棋受攻。','In the opening consider corners, sides and coordination. When a local position settles, look for the largest whole-board direction.','读一局名局的前 30 手，每次停下写出下一手想解决的问题，再揭晓实战。','Study the first 30 moves of a record. Before revealing each move, name the problem it should solve.','library'],
    ['review','复盘只抓三个转折','Find three turning points','先自己回想哪里开始难下，再用 AI 检查。每局最多选三个转折，解释实战的问题，试下一个更稳妥的方案。低搜索量结论先复核。','Recall where the game became difficult before consulting AI. Pick up to three turning points and try a safer alternative. Recheck low-search conclusions.','复盘一盘自己的棋，留下“我漏看了什么”和“下次先检查什么”两句笔记。','Review one of your games. Note what you missed and what you will check next time.','review'],
    ['endgame','收官时比较先后手','Compare endgame choices','先确认双方死活，再比较边界。能迫使对方应手的收官与走完轮到对方的大场不同；不要把还有争议的棋直接当成死棋。','Settle life and death before comparing boundaries. Distinguish forcing endgame moves from moves that give away the initiative.','终局先自己点目，再看 AI 参考；找出一处归属判断不同的区域。','Count a finished position yourself, then compare with AI and examine one disagreement.','play'],
    ['routine','建立可持续的训练循环','Build a repeatable routine','每周安排两盘认真对局、两次短复盘和少量每日读题。难题卡住就降一级；同类错误反复出现时，再集中练习。用几周的变化判断进步。','Plan two thoughtful games, two short reviews and a little daily reading each week. Reduce difficulty when stuck and focus on recurring mistakes. Evaluate progress over weeks.','本周选择一个主题：气、连接、弱棋或收官。周末回顾是否比上周少犯一次同类错误。','Choose one theme this week: liberties, connections, weak groups or endgame. At week end, check whether that mistake happened less often.','practice']
  ];
  function render(en,legacy=false){
    if(root.GoTTraining&&!legacy){const html=render(en,true);return '<details class="training-assessment"><summary>'+(en?'Playing-strength reference (separate from learning)':'对局棋力参考（与课程掌握分开统计）')+'</summary>'+html.slice(html.indexOf('<section class="growth-assessment">'),html.lastIndexOf('</section>'))+'</details>';}
    const t=(z,e)=>en?e:z,x=read(),completed=(x.done||[]).length,pct=Math.round(completed/lessons.length*100);
    const engines=['builtin','gtp','b6','b18'].map(engine=>{const a=estimate(engine),label=engine==='gtp'?t('旧版 KataGo','Legacy KataGo'):engine==='builtin'?t('内置 AI','Built-in AI'):'KataGo '+engine;return `<article class="growth-engine-card"><span>${label}</span><strong>${a?rankLabel(engine,a.level,en):t('样本不足','Need more games')}</strong><small>${a?a.count+t(' 盘样本',' games')+' · '+rankLabel(engine,a.low,en)+'–'+rankLabel(engine,a.high,en):t('完成 3 盘后显示参考','Reference after 3 games')}</small>${a?`<i class="${a.stable?'is-stable':''}">${a.stable?t('近期较稳定','Consistent lately'):t('仍在探索','Still exploring')}</i>`:''}</article>`;}).join('');
    return `<section class="growth-path"><header class="growth-path-hero"><div><span class="growth-eyebrow">${t('学习路径','LEARNING PATH')}</span><h2>${t('入门之后，怎样继续进步','Your path beyond the basics')}</h2><p>${t('选一个主题去实践，再记录结果。逐周回看，比单局输赢更能看出变化。','Choose a theme, practise it, and record what you learn. Weekly patterns tell more than a single result.')}</p><div class="growth-progress"><div><span>${t('练习进度','PRACTICE PROGRESS')}</span><strong>${completed} <i>/ ${lessons.length}</i></strong></div><div class="growth-progress-track"><i style="width:${pct}%"></i></div></div></div><div class="growth-path-index"><span>2.4</span><small>${t('持续练习','KEEP PRACTISING')}</small></div></header><div class="growth-lesson-grid">${lessons.map(([id,z,e,body,bodyEn,task,taskEn,target],i)=>`<details class="growth-lesson" ${i===0?'open':''}><summary><span class="growth-lesson-number">${String(i+1).padStart(2,'0')}</span><span>${t(z,e)}</span><b>${(x.done||[]).includes(id)?'✓': '＋'}</b></summary><div class="growth-lesson-body"><p>${t(body,bodyEn)}</p><p class="growth-practice-prompt"><strong>${t('这次练什么','Practice focus')}</strong>${t(task,taskEn)}</p><div class="growth-actions"><button type="button" class="btn primary" data-growth-go="${target}">${t('去实践','Practise')}</button><button type="button" class="btn ghost" data-growth-done="${id}" aria-pressed="${(x.done||[]).includes(id)}">${t('记录已实践','Mark practised')}</button></div></div></details>`).join('')}</div><section class="growth-assessment"><div class="growth-assessment-heading"><span class="growth-eyebrow">${t('实战校准','PLAYING STRENGTH')}</span><h2>${t('找到势均力敌的对手','Find a well-matched opponent')}</h2><p>${t('连续对局会逐步调整难度。完成至少 3 盘后显示参考，建议 5–8 盘；结果用于匹配对手，不是正式段位。','Consecutive games adjust the difficulty. A reference appears after three games; five to eight are recommended. This helps match opponents and is not a formal rank.')}</p></div><div class="growth-engine-grid">${engines}</div><div class="growth-assessment-actions"><button type="button" class="btn primary" data-growth-assess>${t('开始下一盘测评','Start next assessment game')}</button><p class="dialog-hint">${t('开始前可先导出当前棋谱；离开后可以返回继续。进入复盘、分析、悔棋或载入其他棋局会结束本盘测评。','Export your current record first if needed. You can return after navigating away. Review, analysis, undo, or loading another game ends this assessment.')}</p></div></section><section class="growth-activity-card"><div><span class="growth-eyebrow">${t('保持节奏','KEEP A RHYTHM')}</span><h3>${t('近 13 周练习','Practice over the last 13 weeks')}</h3></div><div id="growthHeatmap"></div></section></section>`;}
  function heatmap(host,en){if(!host)return;host.replaceChildren();const x=read(),end=new Date(),start=new Date(end);start.setDate(end.getDate()-90);start.setDate(start.getDate()-((start.getDay()+6)%7));let active=0;const grid=document.createElement('div');grid.className='activity-grid';grid.setAttribute('role','list');for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const key=day(d),count=(x.days[key]||[]).length;if(count)active++;const cell=document.createElement('span');cell.className='activity-day';cell.dataset.level=String(Math.min(4,count));cell.title=key+' · '+count+(en?' activities':' 次活动');cell.setAttribute('role','listitem');cell.setAttribute('aria-label',cell.title);grid.append(cell);}const note=document.createElement('p');note.textContent=en?`${active} active days · last 13 weeks · darker means more activity`:`近 13 周活跃 ${active} 天 · 颜色越深，练习越多`;host.append(grid,note);}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-growth-go],[data-growth-done],[data-growth-assess]');if(!b)return;if(b.hasAttribute('data-growth-assess'))document.dispatchEvent(new CustomEvent('got:assessment-start'));else if(b.dataset.growthGo)document.dispatchEvent(new CustomEvent('got:home-action',{detail:b.dataset.growthGo}));else{const x=read(),id=b.dataset.growthDone;x.done=x.done||[];if(!x.done.includes(id))x.done.push(id);save(x);activity('method',id);root.GoTLearning?.render();}});
  document.addEventListener('got:learning-lesson-event',e=>{if(e.detail?.type==='solve')activity('lesson',e.detail.lessonId);});
  document.addEventListener('got:learning-library-event',e=>{if(Number(e.detail?.index)>0)activity('record',e.detail.libraryId);});
  document.addEventListener('got:problem-progress',()=>activity('problems','practice'));
  function merge(raw){if(!raw||typeof raw!=='object')return;const x=read();for(const [key,items] of Object.entries(raw.days||{}).slice(-730)){if(/^\d{4}-\d{2}-\d{2}$/.test(key)&&Array.isArray(items))x.days[key]=[...new Set([...(x.days[key]||[]),...items.filter(i=>typeof i==='string'&&i.length<160)])].slice(-100);}x.done=[...new Set([...(x.done||[]),...(Array.isArray(raw.done)?raw.done:[])])].filter(id=>lessons.some(l=>l[0]===id));const valid=(Array.isArray(raw.matches)?raw.matches:[]).filter(r=>r&&['builtin','gtp','b6','b18'].includes(r.engine)&&Number.isInteger(r.level)&&r.level>=1&&r.level<=9&&[0,.5,1].includes(r.outcome)&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)).map(({engine,level,outcome,date})=>({engine,level,outcome,date}));const known=new Set(x.matches.map(r=>JSON.stringify(r)));for(const r of valid)if(!known.has(JSON.stringify(r))){x.matches.push(r);known.add(JSON.stringify(r));}x.matches=x.matches.slice(-60);save(x);}
  root.GoTGrowth={day,read,activity,nextLevel,result,estimate,render,heatmap,merge};
})(window);
